### ISSUE TITLE
Natives module depends on Node.js internals. 

### ISSUE THREAD

**Issue by lightandshadow68** [denkwerk/xliff2excel#1]
When installing via NPM... 

`npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.`

Looks like this point is now, as I receive this error when executing .....

`at req_ (/usr/local/lib/node_modules/xliff2excel/node_modules/natives/index.js:143:24)`

**Comment by lanton1x** [comment]
I got similar warning first, and a complete broken code later, that I cannot find a workaround about, please help:
1) npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
2) My testing framework breaks with the following error trace:
    ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (../../--path--to/node_modules/natives/index.js:143:24)
    at Object.req[as require] (../../--path-to-project's-/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (../../--path-to-project's-/node_modules/s3/node_modules/graceful-fs/graceful-fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internals/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loadr.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (../../--path-to-project's-/node_modules/s3/node_modules/graceful-fs/graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Modules._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Modules._load (internal/modules/cjs/loader.js:877:14)
    at Modules.require (internal/modules/cjs/loader.js:1019:19)

**Comment by saitho** [comment]
Dependency update helped. See PR #2.

Updating everything but chalk to latest versions does not break functionality.
I was able to generate a xlsx file from xlf.
